### ISSUE TITLE
Switch to pydantic v2 or pin fractal-tasks-core to <1.2.0

### ISSUE THREAD

**Issue by tcompa** [leukemia-kispi/operetta-compose#2]
Hi there,

`fractal-tasks-core` 1.2.0 moved from Pydantic v1 to Pydantic v2, but operetta-compose still uses the v1 logic, see
```python
from pydantic.v1.decorator import validate_arguments

@validate_arguments
def stardist_segmentation(..)
```

This can at least lead to confusing errors, or to tasks just failing.

--

I suggest one of these two approaches:
1. Provisionally pin fractal-tasks-core dependency to `<=1.1.1` in pyproject.toml
2. Fully move to pydantic v2. After a quick look at the code (to be double-checked), I think this would mostly consist in replacing `from pydantic.v1.decorator import validate_arguments` with `from pydantic import validate_call`, and then using the new decorator in front of task functions.

(cc @jluethi @lorenzocerrone)

**Comment by fdsteffen** [comment]
Thanks @tcompa! Great, will adapt the code to use pydantic v2.
